const messageofthedaylist = [
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
  "You are never alone; God walks with you. Deuteronomy 31:6 —\n\nThe Lord your God goes with you; he will never leave you.",
  "Peace comes not from circumstances, but from trust in Him. Isaiah 26:3 —\n\nYou will keep in perfect peace those whose minds are steadfast.",
  "Even in weakness, His strength is revealed. 2 Corinthians 12:9 —\n\nMy grace is sufficient for you, for my power is made perfect in weakness.",
  "Let faith arise even when answers delay. Hebrews 11:1 —\n\nFaith is the assurance of things hoped for.",
  "God hears every whispered prayer. Psalm 34:17 —\n\nThe righteous cry out, and the Lord hears them.",
  "In Him, you are a new creation. 2 Corinthians 5:17 —\n\nIf anyone is in Christ, the new creation has come.",
  "Nothing can separate you from His love. Romans 8:39 —\n\nNothing will be able to separate us from the love of God.",
  "His plans for you are good. Jeremiah 29:11 —\n\nFor I know the plans I have for you, declares the Lord.",
  "When you are tired, He gives rest. Matthew 11:28 —\n\nCome to me, all who are weary and burdened, and I will give you rest.",
  "God is your refuge in times of trouble. Psalm 46:1 —\n\nGod is our refuge and strength, an ever-present help in trouble.",
];

export default messageofthedaylist;